// Conhecimento fixo da Leadrix para os agentes. Espelha src/data/leadrix.js e
// src/data/abmPlaybook.js — ao mudar a taxonomia lá, atualize aqui.
// Mantido estável (sem datas, sem ids) para o cache do prompt funcionar.

export const LEADRIX_KNOWLEDGE = `# A Leadrix
Consultoria que transforma inteligência artificial em decisões, processos, capacidades e crescimento para empresas médias e grandes, na interseção entre gestão, pessoas e tecnologia. Tagline: "Lidere seu mercado com IA". Ciclo: Organizar × Automatizar × Educar × Adotar × Crescer.

Princípios: (1) negócio antes da tecnologia — problema, consequência e indicador orientam a escolha técnica; (2) quatro pilares conectados que avançam como sistema; (3) implantação acompanhada, com responsáveis, riscos e critérios de escala desde o diagnóstico. Governança: regras de uso, dados permitidos, supervisão humana e indicadores proporcionais ao risco.

## Os quatro pilares de entrega
1. Estruturas Organizacionais Híbridas — redesenhar papéis, responsabilidades e rotinas para pessoas, agentes, sistemas e dados operarem como uma organização. Entregas: mapeamento de funções e decisões; redesenho de papéis entre pessoas, agentes e sistemas; modelo de supervisão e exceções; indicadores de capacidade, qualidade, adoção e produtividade.
2. Agentes e Processos Automatizados para Eficiência — agentes e automação para reduzir desperdício, retrabalho, custo e tempo, com supervisão humana onde há julgamento. Entregas: diagnóstico e redesenho de processos; priorização por impacto, custo, prazo, risco e maturidade; integração de agentes, documentos, dados e sistemas; regras e indicadores.
3. Educação e Adoção Produtiva — formar líderes e equipes para usar IA no trabalho real. Entregas: Curso de Formação Leadrix e Workshop Mensal; workshops in company por função; formação de multiplicadores; Playbook de IA.
4. Novos Negócios, Linhas de Receita e Spin-offs — transformar conhecimento, dados e capacidades em produtos, serviços e empresas derivadas. Entregas: mapeamento de ativos; teses de negócio; prototipação e tese econômico-financeira; modelo de implantação, parceria ou spin-off.

Portas de entrada: Margem e Capacidade (eficiência), Adoção e Liderança (educação e redesenho), Crescimento e Diferenciação (novos negócios). A porta de entrada padrão é o Diagnóstico Leadrix.

## Os quatro mercados
- Serviços B2B (consultorias, assessorias, agências, escritórios especializados, serviços profissionais). Decisores: sócios, CEOs, diretores de operações. Dores: conhecimento disperso, margem pressionada por retrabalho, prazos, uso informal de IA, metodologia que não vira produto. Indicadores: horas por entrega, margem por serviço, prazo médio, capacidade por equipe, adoção, receita de novas ofertas.
- Indústria. Decisores: diretores de operações, transformação, excelência e unidades de negócio. Dores: processos em planilha e e-mail, informação dispersa entre ERP e documentos, decisões reativas, POCs sem critério de escala, baixa adesão operacional. Indicadores: custo por processo, tempo de ciclo, erro e retrabalho, qualidade, capacidade liberada, prazo de retorno.
- Varejo e Franquias. Decisores: diretores de operações, rede, expansão, comercial e transformação. Dores: maturidade desigual entre lojas, dados atrasados, sobrecarga na ponta, padrões que se degradam na execução, tecnologia abandonada. Indicadores: conversão por unidade, tempo de atendimento, aderência ao processo, adoção por perfil, margem por unidade, tempo de treinamento.
- Empresas Digitais. Decisores: CEO, COO, líderes de produto, tecnologia, growth e operações. Dores: experimentos competindo por recursos, funcionalidades copiáveis, custo de tecnologia acima do valor, automações isoladas, tensão entre velocidade e segurança. Indicadores: custo de aquisição, custo de servir, tempo de ciclo de produto, retenção, receita por cliente, receita de produtos com IA.

## Account Based Marketing (referencial)
ABM trata cada conta de alto valor como um mercado próprio: seleção pelo ICP, mapa do comitê de compra, proposta de valor personalizada e toques orquestrados em vários canais.
- Níveis: 1:1 (contas estratégicas, tudo sob medida, sócios envolvidos); 1:few (clusters do mesmo microssegmento); 1:many (escala, conteúdo por segmento, workshops abertos).
- Comitê de compra: patrocinador econômico, campeão, influenciador técnico (TI, dados, segurança, jurídico), usuários, bloqueadores potenciais. Cobrir mais de uma persona (multi-threading) é o principal antídoto contra oportunidades paradas.
- Insight antes do pitch; orquestração multicanal planejada; vendas e marketing com um plano por conta; land and expand pelos pilares conectados; medir cobertura do comitê, dias por etapa versus SLA, taxa de avanço, custo de venda e ROI por conta.

## Contexto estratégico de ABM da Leadrix
Tese central: usar ABM para selecionar empresas médias nas quais seja possível formular uma hipótese concreta de transformação, mobilizar o grupo decisor e iniciar a relação por uma entrega de menor risco que gere evidência para projetos maiores. Cinco princípios: contas antes de leads; problemas econômicos antes de ferramentas; grupo decisor antes de contato isolado; diagnóstico e evidência antes de projetos extensos; entrada por uma dor e expansão pelos quatro pilares.

Pergunta que orienta cada conta: onde esta empresa está perdendo margem, capacidade, qualidade, velocidade ou oportunidade de receita porque sua forma de operar ainda não incorporou adequadamente a IA?

Universo de contas: empresas de aproximadamente R$ 50 milhões a R$ 1 bilhão de faturamento, com complexidade que justifique transformação e sem estrutura interna de grande corporação. Distribuição: 10 a 12 contas nível 1 (1:1), 25 a 35 nível 2 (1:few), demais em relacionamento editorial e monitoramento. Prioridade por mercado: Serviços B2B e Indústria muito alta; Varejo e Franquias alta; Empresas Digitais seletiva (entram quando há transformação interfuncional relevante — automação simples é internalizada).

Pontuação da conta ideal (soma 100): tensão econômica 25, complexidade operacional 20, estágio de IA 15, condições de implantação 15, momento de compra 10, potencial de expansão 10, acesso e proximidade de prova 5. De 80 pontos: nível 1. De 65 a 79: nível 2. De 50 a 64: relacionamento. Abaixo de 50: fora da operação ativa. Bloqueiam a priorização, independentemente da nota: sem patrocinador executivo ou responsável pelo processo; interesse limitado a ferramenta ou palestra; empresa pequena demais; organização capaz de internalizar tudo; sem acesso a dados e responsáveis; demanda de desenvolvimento sob encomenda sem aderência ao método.

Sinais de intenção que ativam o ABM: meta de produtividade ou margem sem ampliar equipe; expansão, aquisição ou reorganização; implantação ou troca de ERP, CRM ou plataforma de dados; contratação de liderança de transformação, inovação, tecnologia ou operações; programa de IA sem critério de priorização; uso não autorizado de ferramentas; iniciativas presas em prova de conceito; dificuldade de contratar especialistas; processos terceirizados de alto custo; mudança regulatória que aumenta documentação; programa de educação em IA desconectado de processos. Um sinal não gera apresentação comercial: gera hipótese sobre o que acontece e sobre qual indicador é afetado.

Campanhas (nascem de problemas, não de produtos): Crescer sem ampliar a estrutura (Serviços B2B); Da experimentação ao portfólio (todos); IA no fluxo real da operação (Indústria); Capacidade com padrão em cada unidade (Varejo e Franquias); Comprar o trabalho pronto / Autopilot (contas com terceirização relevante). Autopilot só vale com recorrência, entrada e saída definidas, trabalho por regras, pouco julgamento, volume, indicador verificável, orçamento identificável e exceções encaminháveis — sem isso, vira projeto customizado de margem imprevisível.

Jornada comercial por conta: (1) sinal e hipótese; (2) conteúdo executivo específico; (3) conversa de diagnóstico; (4) diagnóstico pago ou workshop de trabalho; (5) piloto com prova de valor e critérios de continuidade; (6) implantação e expansão. Educação pode abrir a conta, mas workshop que não produz casos de uso, responsáveis, critérios e próximos passos rebaixa a Leadrix à categoria de treinamento.

Grupo decisor por papel, com o que cada um defende e a evidência mais útil: CEO (competitividade e margem — memorando executivo e portfólio priorizado); COO/operações (produtividade e qualidade — mapa do processo, linha de base e piloto); Pessoas/RH (adoção e competências — arquitetura de aprendizagem, Playbook, indicadores de adoção); Inovação/estratégia/produto (priorização e escala — matriz de portfólio); CIO/CTO/segurança (arquitetura, dados e risco — fluxo de dados, controles, integração); CFO (retorno e previsibilidade — justificativa de investimento e prazo de retorno); Jurídico/privacidade (limites e responsabilidades — matriz de riscos); Compras (escopo e condições — critérios de aceite). A conta não está desenvolvida enquanto depender de uma pessoa: o mínimo é patrocinador econômico + responsável operacional + aprovador técnico ou de risco.

Estrutura da mensagem (voz Sábio e Explorador): apresentar sinal ou tensão verificável; formular hipótese sobre processo ou organização; relacionar a hipótese a uma consequência econômica; demonstrar por que merece investigação; convidar para uma decisão específica. Nunca presumir que a dor existe — apresentar hipótese que o executivo possa confirmar, corrigir ou rejeitar, sem fabricar intimidade.

Métricas que comandam a operação (por conta): cobertura (grupo decisor mapeado, contatos por conta, hipótese documentada), engajamento (duas ou mais áreas interagindo, executivos presentes), conversão (avanço para diagnóstico, diagnóstico que vira piloto, tempo até oportunidade, taxa de vitória), expansão (receita adicional, pilares por cliente, recorrência). Downloads e taxas de abertura interpretam atividade, não comandam: uma conta com três decisores envolvidos vale mais que cem leads de conteúdo genérico.

## Voz da marca
Português do Brasil. "Nós"/"a Leadrix" para a empresa; "você/sua empresa" para o leitor. Consultiva, sênior e anti-hype: credibilidade vem de método, governança e impacto mensurável, nunca de adjetivos. Evite "revolucionário", "mágico", "disruptivo", "o futuro chegou", emojis, excesso de exclamações e números inventados. Movimentos típicos: contrastar a pergunta errada ("qual ferramenta usar?") com a certa ("o que muda na operação, na decisão e no resultado?"); nomear o risco real ("o risco não é não usar IA; é usar IA sem método e chamar isso de inovação"). CTAs consultivos: Agendar diagnóstico, Começar pelo diagnóstico, Falar com a Leadrix, Mapear oportunidades de IA. Fechamento assinatura: "É aí que a Leadrix entra."`
